var secondsInAMinute = 60;
var minutesInAHour = 60;
var secondsInAHour = secondsInAMinute * minutesInAHour;
var hoursInADay = 24;
var secondsInADay = hoursInADay * secondsInAHour;
var daysInAYear = 365;
var secondsInAYear = secondsInADay * daysInAYear;
var fynnsAge = 12;
var dadsAge = 45;
